basePath: /
consumes:
- application/json
host: localhost:3000
info:
  contact:
    email: ashutoshgngwr@gmail.com
    name: Ashutosh Gangwar
    url: https://ashutoshgngwr.github.io
  description: APIs for a simple trello board application to manage users and their
    tasks.
  license:
    name: Proprietary
  title: backend-assignment
  version: 1.0.0
paths:
  /boards:
    post:
      consumes:
      - application/json
      description: Creates a new board and sets the current user as its admin
      operationId: createBoard
      parameters:
      - in: body
        name: Body
        schema:
          properties:
            name:
              type: string
              x-go-name: Name
          type: object
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/created'
        "400":
          $ref: '#/responses/errored'
        "403":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
  /boards/{boardID}:
    get:
      consumes:
      - application/json
      description: Check if a logged in user has access to the given board
      operationId: getBoard
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/getBoard'
        "400":
          $ref: '#/responses/errored'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
  /boards/{boardID}/archive:
    get:
      consumes:
      - application/json
      description: Archive board with given ID
      operationId: archiveBoard
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      produces:
      - application/json
      responses:
        "202":
          $ref: '#/responses/archiveBoard'
        "400":
          $ref: '#/responses/errored'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
  /boards/{boardID}/status:
    get:
      consumes:
      - application/json
      description: List all status for a given board
      operationId: listStatus
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - format: uint64
        in: query
        name: limit
        type: integer
        x-go-name: Limit
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/listResponse'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - status
    post:
      consumes:
      - application/json
      description: Create a new status for a given board
      operationId: createStatus
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - in: body
        name: Body
        schema:
          properties:
            title:
              type: string
              x-go-name: Title
          type: object
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/created'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - status
  /boards/{boardID}/status/{statusID}:
    delete:
      consumes:
      - application/json
      description: Delete status for a given board
      operationId: deleteStatus
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - in: path
        name: statusID
        required: true
        type: string
        x-go-name: StatusID
      produces:
      - application/json
      responses:
        "202":
          $ref: '#/responses/deleteStatus'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - status
    get:
      consumes:
      - application/json
      description: Get status details for a given board
      operationId: getStatus
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - in: path
        name: statusID
        required: true
        type: string
        x-go-name: StatusID
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/getStatus'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - status
  /boards/{boardID}/tasks:
    get:
      consumes:
      - application/json
      description: List tasks on a given board
      operationId: listTask
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - format: uint64
        in: query
        name: limit
        type: integer
        x-go-name: Limit
      - description: list tasks for this status only
        format: uint64
        in: query
        name: status_id
        type: integer
        x-go-name: StatusID
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/listResponse'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - task
    post:
      consumes:
      - application/json
      description: Create a new task on a given board
      operationId: createTask
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - in: body
        name: Body
        schema:
          properties:
            assignee_id:
              format: uint64
              type: integer
              x-go-name: AssigneeID
            description:
              type: string
              x-go-name: Description
            due_date:
              format: date-time
              type: string
              x-go-name: DueDate
            status_id:
              format: uint64
              type: integer
              x-go-name: StatusID
            title:
              type: string
              x-go-name: Title
          type: object
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/created'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - task
  /boards/{boardID}/tasks/{taskID}:
    delete:
      consumes:
      - application/json
      description: Delete task on a given board
      operationId: deleteTask
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - format: uint64
        in: path
        name: taskID
        required: true
        type: integer
        x-go-name: TaskID
      produces:
      - application/json
      responses:
        "202":
          $ref: '#/responses/deleteTaskResponse'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - task
    get:
      consumes:
      - application/json
      description: Get task on a given board
      operationId: getTask
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - format: uint64
        in: path
        name: taskID
        required: true
        type: integer
        x-go-name: TaskID
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/getTask'
        "400":
          $ref: '#/responses/errored'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - task
    put:
      consumes:
      - application/json
      description: Update task on a given board
      operationId: updateTask
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - in: body
        name: Body
        schema:
          properties:
            assignee_id:
              format: uint64
              type: integer
              x-go-name: AssigneeID
            description:
              type: string
              x-go-name: Description
            due_date:
              format: date-time
              type: string
              x-go-name: DueDate
            status_id:
              format: uint64
              type: integer
              x-go-name: StatusID
            title:
              type: string
              x-go-name: Title
          type: object
      - format: uint64
        in: path
        name: taskID
        required: true
        type: integer
        x-go-name: TaskID
      produces:
      - application/json
      responses:
        "202":
          $ref: '#/responses/updateTaskResponse'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - task
  /boards/{boardID}/unarchive:
    get:
      consumes:
      - application/json
      description: Unarchive board with given ID
      operationId: unarchiveBoard
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      produces:
      - application/json
      responses:
        "202":
          $ref: '#/responses/unarchiveBoard'
        "400":
          $ref: '#/responses/errored'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
  /boards/{boardID}/users:
    delete:
      consumes:
      - application/json
      description: Removes the provided user to the given board
      operationId: removeUser
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - in: body
        name: Body
        schema:
          properties:
            user_id:
              format: uint64
              type: integer
              x-go-name: UserID
          type: object
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/assignOrRemoveUser'
        "400":
          $ref: '#/responses/errored'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - user
    get:
      consumes:
      - application/json
      description: Lists all users assigned to a given board
      operationId: listUser
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - format: uint64
        in: query
        name: limit
        type: integer
        x-go-name: Limit
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/listResponse'
        "400":
          $ref: '#/responses/errored'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - user
    put:
      consumes:
      - application/json
      description: Adds the provided user to the given board
      operationId: assignUser
      parameters:
      - format: uint64
        in: path
        name: boardID
        required: true
        type: integer
        x-go-name: BoardID
      - in: body
        name: Body
        schema:
          properties:
            user_id:
              format: uint64
              type: integer
              x-go-name: UserID
          type: object
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/assignOrRemoveUser'
        "400":
          $ref: '#/responses/errored'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - board
      - user
  /users/{userID}:
    get:
      consumes:
      - application/json
      description: Get a user by their ID
      operationId: getUser
      parameters:
      - in: path
        name: userID
        required: true
        type: string
        x-go-name: UserID
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/getUser'
        "404":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - user
  /users/login:
    post:
      consumes:
      - application/json
      description: Login a user using credentials to issue a session token
      operationId: loginUser
      parameters:
      - in: body
        name: Credentials
        required: true
        schema:
          properties:
            email:
              type: string
              x-go-name: Email
            password:
              type: string
              x-go-name: Password
          type: object
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/loginResponse'
        "400":
          $ref: '#/responses/errored'
        "403":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - user
  /users/logout:
    get:
      consumes:
      - application/json
      description: Revokes the current session token for the user
      operationId: logoutUser
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/logoutResponse'
        "403":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      tags:
      - user
  /users/signup:
    post:
      consumes:
      - application/json
      operationId: signupUser
      parameters:
      - in: body
        name: User
        required: true
        schema:
          properties:
            email:
              type: string
              x-go-name: Email
            name:
              type: string
              x-go-name: Name
            password:
              type: string
              x-go-name: Password
          type: object
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/created'
        "400":
          $ref: '#/responses/errored'
        "500":
          $ref: '#/responses/errored'
      schemes:
      - http
      - https
      summary: Register a new user with the system.
      tags:
      - user
produces:
- application/json
responses:
  archiveBoard:
    description: Successfully archived
  assignOrRemoveUser:
    description: Indicates operation success
  created:
    description: |-
      Returned on successful resource creation. It also contains the path of created
      resource on the server.
    schema:
      properties:
        href:
          type: string
          x-go-name: Href
      type: object
  deleteStatus:
    description: status deleted successfully
  deleteTaskResponse:
    description: Successful delete
  errored:
    description: A response that indicates error in performed operation
    schema:
      properties:
        error:
          type: string
          x-go-name: Error
      type: object
  getBoard:
    description: Indicates that user is assigned to the board
  getStatus:
    description: task status details
    schema:
      properties:
        board_id:
          format: uint64
          type: integer
          x-go-name: BoardID
        id:
          format: uint64
          type: integer
          x-go-name: ID
        title:
          type: string
          x-go-name: Title
      type: object
  getTask:
    description: Returned task
    schema:
      properties:
        assignee_id:
          format: uint64
          type: integer
          x-go-name: AssigneeID
        assigner_id:
          format: uint64
          type: integer
          x-go-name: AssignerID
        description:
          type: string
          x-go-name: Description
        due_date:
          format: date-time
          type: string
          x-go-name: DueDate
        owner_id:
          format: uint64
          type: integer
          x-go-name: OwnerID
        status_id:
          format: uint64
          type: integer
          x-go-name: StatusID
        title:
          type: string
          x-go-name: Title
      type: object
  getUser:
    description: Returns requested user
    schema:
      properties:
        email:
          type: string
          x-go-name: Email
        id:
          format: uint64
          type: integer
          x-go-name: ID
        is_admin:
          type: boolean
          x-go-name: IsAdmin
        name:
          type: string
          x-go-name: Name
      type: object
  listResponse:
    description: A list of requested resources with their location
    schema:
      properties:
        hrefs:
          items:
            type: string
          type: array
          x-go-name: Hrefs
      type: object
  loginResponse:
    description: loginReponse returns a session token in Authorization header on successful
      login
    headers:
      Authorization:
        description: Bearer <token>
        type: string
  logoutResponse:
    description: indicates successful logout
  unarchiveBoard:
    description: Successfully unarchived
  updateTaskResponse:
    description: Successful update
schemes:
- http
securityDefinitions:
  api_key:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
